# Generated by Django 5.1.1 on 2024-10-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_certificate_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('coding', 'Coding Skills'), ('professional', 'Professional Skills')], default='Coding', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.ImageField(default=2, upload_to='certificates/'),
            preserve_default=False,
        ),
    ]
