# Generated by Django 5.1.2 on 2024-11-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_resume_delete_education_delete_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Projektbild'),
        ),
    ]
